from .edital_schemas import EditalInSchema, EditalOutSchema, EditalFileInSchema
from .relatorio_bolsista_schemas import RelatorioBolsistaInSchema, RelatorioBolsistaOutSchema
from .relatorio_coordenador_schemas import RelatorioCoordenadorInSchema, RelatorioCoordenadorOutSchema
