"""empty message

Revision ID: 1ce529440d61
Revises: e44cf762ca03
Create Date: 2025-08-26 00:56:33.076653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce529440d61'
down_revision = 'e44cf762ca03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.drop_column('vagas_ocupadas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vagas_ocupadas', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
