"""empty message

Revision ID: 447cdbb800bc
Revises: 821acadfdbcb
Create Date: 2025-07-07 16:20:29.155633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '447cdbb800bc'
down_revision = '821acadfdbcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presenca', schema=None) as batch_op:
        batch_op.drop_column('presente')
        batch_op.drop_column('justificativa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presenca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('justificativa', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('presente', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
