"""empty message

Revision ID: 821acadfdbcb
Revises: d5e552c1bd1b
Create Date: 2025-07-04 14:09:13.099180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821acadfdbcb'
down_revision = 'd5e552c1bd1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edital', schema=None) as batch_op:
        batch_op.alter_column('caminho_arquivo',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edital', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('caminho_arquivo',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
