"""empty message

Revision ID: bf200b0a56d9
Revises: 447cdbb800bc
Create Date: 2025-07-14 16:03:32.518712

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bf200b0a56d9'
down_revision = '447cdbb800bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presenca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presente', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('inscricao_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint('uq_aluno_frequencia_semanal', type_='unique')
        batch_op.create_unique_constraint('uq_inscricao_frequencia_semanal', ['inscricao_id', 'frequencia_semanal_id'])
        batch_op.drop_constraint('presenca_aluno_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'inscricao', ['inscricao_id'], ['id'])
        batch_op.drop_column('aluno_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presenca', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aluno_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('presenca_aluno_id_fkey', 'aluno', ['aluno_id'], ['id'])
        batch_op.drop_constraint('uq_inscricao_frequencia_semanal', type_='unique')
        batch_op.create_unique_constraint('uq_aluno_frequencia_semanal', ['aluno_id', 'frequencia_semanal_id'],
                                          postgresql_nulls_not_distinct=False)
        batch_op.drop_column('inscricao_id')
        batch_op.drop_column('presente')

    # ### end Alembic commands ###
