"""empty message

Revision ID: f0aebe6fc457
Revises: e44cf762ca03
Create Date: 2026-03-03 12:50:57.173687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0aebe6fc457'
down_revision = 'e44cf762ca03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mostrar_para_alunos', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.drop_column('mostrar_para_alunos')

    # ### end Alembic commands ###
