"""empty message

Revision ID: fb22c7fc4d4e
Revises: f0aebe6fc457
Create Date: 2026-04-22 15:52:47.331559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb22c7fc4d4e'
down_revision = 'f0aebe6fc457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.Enum('PESQUISA', 'EXTENSAO', name='tipoprojeto'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projeto', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
