name: NEPA CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e
            cd /home/nepa/NEPA-api

            git pull origin main
            python3 -m venv .venv
            source .venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            
            flask db upgrade

            sudo systemctl daemon-reload
            sudo systemctl restart nepa-api
            sudo systemctl status nepa-api --no-pager
            journalctl -u nepa-api --since "15 minutes ago" --no-pager