name: NEPA CI

on:
  push:
    branches: [ "main", "development" ]
  pull_request:
    branches: [ "main", "development" ]

permissions:
  contents: read

env:
  FLASK_APP: wsgi.py
  FLASK_ENV: testing
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  TEST_DATABASE_URI: 'sqlite:///:memory:'
  API_TITLE: NEPA
  API_VERSION: v2
  OPENAPI_VERSION: 3.0.2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Installs the ruff action and adds to PATH
        uses: astral-sh/ruff-action@v3

      - name: Check code with Ruff
        run: ruff check --output-format=github

      - name: Check code formatting with Ruff
        run: ruff format --diff
        continue-on-error: true

      - name: Create mock .env file
        run: |
          touch .env
          echo FLASK_APP=wsgi.py >> .env

      - name: Test with pytest
        run: pytest -v --disable-warnings
